## Problem 1:
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [36]:
import numpy as np
#We are creating function similar to numpy.vander

def power_mat(arr,N,incr=True):       

    if incr:
        result = np.mat([arr**i for i in range(N)]).transpose()
        return result
    else:
        result = np.mat([arr**(N-i-1) for i in range(N)]).transpose()
        return result
        
    
if __name__ == "__main__":  
    #Get array and number of columns and increasing order
    
    a= input("Enter array of numbers separated by space: ").split()    
    N= int(input("Number of columns in power matrix: "))
    incr = bool(int(input("Enter 0 or 1 as truth value for increasing order: ")))
    print(incr)
    
    
    #convert array into integer numpy array
    arr = np.array(a,dtype=int)
    
    #Call power matrix function
    res = power_mat(arr,N,incr)
    
    #Display output 
    print('\n\n',res,end='\n\n')      
    print('in built vander:\n',np.vander(arr,N,incr))


Enter array of numbers separated by space: 1 2 3 5
Number of columns in power matrix: 3
Enter 0 or 1 as truth value for increasing order: 1
True


 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]

in built vander:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


## Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
    
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below


In [ ]:
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values

In [50]:
import numpy as np

def mov_avg(a,k):
    #convert sequence into integer numpy array
    arr = np.array(x,dtype=int)
    n= len(arr)
    #Initialize array for storing moving average
    m_avg = []
    sum1 = 0    
    for i in range(n-k+1):
        for j in range(k):
            sum1 = sum1+arr[i+j]
        avg = sum1/k
        m_avg.append(avg)
        sum1=0
        #display output
    print("Moving average array of sequence over interval ",k,"is :\n",m_avg)

        
#Input the sequence and window size and Test function
x = input("Enter sequence of numbers separated by space: ").split()
k = int(input("Enter positive window size 'k' for moving average:  "))

mov_avg(x,k)    

Enter sequence of numbers separated by space: 1 2 3 5 6 77 8
Enter positive window size 'k' for moving average:  4
Moving average array of sequence over interval  4 is :
 [2.75, 4.0, 22.75, 24.0]


### Question:
    
    Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [51]:
#Testin g for given test case
test_array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
test_k = 3
mov_avg(test_array,test_k)

Moving average array of sequence over interval  3 is :
 [2.0, 3.3333333333333335, 4.666666666666667, 29.333333333333332, 30.333333333333332]
